export enum Feature {
	SUBDOMAIN = "SUBDOMAIN",
	HEADER_ANALYSIS = "HEADER_ANALYSIS",
	PORT_SCAN = "PORT_SCAN",
	DIR_BRUTE = "DIR_BRUTE",
	TLS_ANALYSIS = "TLS_ANALYSIS",
	CLOUD_ENUM = "CLOUD_ENUM",
	VULN_SCAN = "VULN_SCAN",
	TEAM_COLLAB = "TEAM_COLLAB",
	UNLIMITED_SCANS = "UNLIMITED_SCANS",
	TECH_DETECT = "TECH_DETECT",
}
